query findOrder($bestellNr: Long) {
  orders (orderId: $bestellNr) {
    id
    mode
    total
    orderDate
    status
    customer {
      id
      firstName
      lastName
    }
    orderItems {
      unitPrice
      product {
        name
        minPrice
        listPrice
      }
      order {
        id
      }
    }

  }
}
